// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoISUGgRvxRzBngymgFjxpv-DjxpOGZNo',
    appId: '1:202194120197:web:e42ea9ee0c97fa17d7366c',
    messagingSenderId: '202194120197',
    projectId: 'ug-467',
    authDomain: 'ug-467.firebaseapp.com',
    storageBucket: 'ug-467.appspot.com',
    measurementId: 'G-HK0MZDP57W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7nOF59QSVJitELBgcZFuEf9jtJhKrar8',
    appId: '1:202194120197:android:075567e2de74d76dd7366c',
    messagingSenderId: '202194120197',
    projectId: 'ug-467',
    storageBucket: 'ug-467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7aFwuPzZR5u4yYXNCElVRgXX_9TbMZBE',
    appId: '1:202194120197:ios:0cc275e150a59fd8d7366c',
    messagingSenderId: '202194120197',
    projectId: 'ug-467',
    storageBucket: 'ug-467.appspot.com',
    iosBundleId: 'com.example.assignmentProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7aFwuPzZR5u4yYXNCElVRgXX_9TbMZBE',
    appId: '1:202194120197:ios:0047d00a493334f8d7366c',
    messagingSenderId: '202194120197',
    projectId: 'ug-467',
    storageBucket: 'ug-467.appspot.com',
    iosBundleId: 'com.example.assignmentProject.RunnerTests',
  );
}
